### PR TITLE
unpacking negative fixint, uint64 + tests

### LINKED ISSUE #6: reading negative fixint (e.g. -27)
### Expected behaviour

It should read small negative number (negative fixint)

like:
```
81 a1 61 e5
```

I would expect object:
```
{"a":-27}
```

### Actual behaviour

I got exception:

```
java.lang.IllegalStateException: Msgpack format tag not yet supported: 0x-f
	at com.squareup.moshi.MsgpackReader.doPeek(MsgpackReader.kt:377) ~[moshipack-1.0.0-beta.jar:?]
	at com.squareup.moshi.MsgpackReader.hasNext(MsgpackReader.kt:139) ~[moshipack-1.0.0-beta.jar:?]
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:67) ~[moshi-kotlin-1.6.0.jar:?]
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137) ~[moshi-1.6.0.jar:?]
```
### Steps to reproduce behaviour

Use code example
```kotlin
data class NegativeFixInt(val a: Int)

fun main(args: Array<String>) {
    val moshiPack = MoshiPack()
    val test = byteArrayOf(0x81.toByte(), 0xa1.toByte(), 0x61.toByte(), 0xe5.toByte())
    val r = moshiPack.unpack<NegativeFixInt>(test)
    assert(r.a == -27)
}
```

### Suggestion how to fix it

In file: https://github.com/davethomas11/MoshiPack/blob/0267e1dbecf4e27be07282a44a126cce30a6fc57/moshipack/src/main/kotlin/com/squareup/moshi/MsgpackReader.kt#L364

replace
```kotlin
in 0..MsgpackFormat.FIX_INT_MAX,
```

to
```kotlin
in MsgpackFormat.FIX_INT_MIN..MsgpackFormat.FIX_INT_MAX,
```

### PR DESCRIPTION
**Pull request by mateuszkj**
fixes #6 + tests for negative numbers

### CODE REVIEW

**Comment by beeender** [comment]
@davethomas11 would you please merge this change? Missing uint64 decoding is a blocking issue for me. thanks.

**Comment by davethomas11** [comment]
Thanks for commenting and the PR. Just saw this now. I will merge this.

**Comment by ShaunPlummer** [comment]
Is this going to be merged?

**Comment by davethomas11** [comment]
Yes! Let’s see if I can actually do it this time with out forgetting. 😂

See your PR too. Thanks for contribution.

**Review by davethomas11 — APPROVED** [review]

**Pull request merged**
